language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

before_install:
  - nvm install node
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction

before_script:
  - npm install

script:
  - vendor/bin/phpunit
  - composer run phpcs

after_success:
  - npm run semantic-release
