language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - cd admin
  - npm install
  - cd ..

script:
  - vendor/bin/phpunit

after_success:
  - npm run semantic-release
